version: "3.8"

services:
  backend:
    image: chandrasekar1158/springboot_cicd_pipeline:latest
    container_name: springboot-backend-container
    ports:
      - "8080:8080"

    environment:

      # =========================
      # DATABASE
      # =========================
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${DB_DRIVER}

      # =========================
      # JPA
      # =========================
      SPRING_JPA_DATABASE_PLATFORM: ${JPA_DIALECT}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${DDL_AUTO}

      # =========================
      # LOGGING
      # =========================
      LOGGING_LEVEL_ORG_HIBERNATE_SQL: ${LOG_LEVEL_SQL}

      # =========================
      # AWS S3
      # =========================
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY: ${AWS_SECRET_KEY}

      # =========================
      # SPRING
      # =========================
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}

      # =========================
      # ACTUATOR
      # =========================
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
      MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS}

      # =========================
      # HIKARI
      # =========================
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT}
      SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE}
      SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE}

    networks:
      - backend-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

    ######################################### PREVIOUS config mysql inside Dcoker ###############################################3
#  version: "3.8"
#
#  services:
#    mysql:
#      image: mysql:8.0
#      container_name: mysql-container
#      environment:
#        MYSQL_ROOT_PASSWORD: Sekar@4711
#        MYSQL_DATABASE: basic
#      ports:
#        - "3307:3306"
#      networks:
#        - backend-network
#      volumes:
#        - mysql-data:/var/lib/mysql
#
#    backend:
#      # 1 This build based on the latest jar generated and by using the Docker file
#      # build:
#      #   context: .
#      #   dockerfile: Dockerfile
#      # 2 This one is for pulling image from docker hub not from latest image generated by using the latest Jar and Docker File
#      image: chandrasekar1158/springboot_cicd_pipeline:latest
#      container_name: backend-container
#      ports:
#        - "8080:8080"
#      depends_on:
#        - mysql
#      environment:
#        SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/basic
#        SPRING_DATASOURCE_USERNAME: root
#        SPRING_DATASOURCE_PASSWORD: Sekar@4711
#      networks:
#        - backend-network
#      # Uncomment if Actuator is enabled
#      healthcheck:
#        test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
#        interval: 30s
#        retries: 5
#
#  networks:
#    backend-network:
#      driver: bridge
#
#  volumes:
#    mysql-data:
